### ISSUE TITLE
Numerical problem in generate_random_spd_matrix

### ISSUE THREAD

**Issue by IanFla** [sebastian-engelke/graphicalExtremes#1]
In generate_random_spd_matrix from https://github.com/sebastian-engelke/graphicalExtremes/blob/master/R/generate_examples.R, I found that there would be numerical problem when we set 'd' to be an odd integer like 3, 5, 7 .... 

Actually, if we run:
1. set.seed(1)
2. generate_random_spd_matrix(3)

An asymmetric matrix would be generated: 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/51277149/190041131-636694ab-f401-4734-bf91-b0a58df7338f.png">

This doesn't raise any problem on my macbook but will become a problem in Unix : 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/51277149/190041421-66d77601-8e7b-4435-ad96-29f0bfb59bc3.png">

**Comment by ManuelHentschel** [comment]
Thanks for submitting this issue and the corresponding PR! Could you please specify which os and version of R give you the error? I could not reproduce it on windows or linux (wsl).

**Comment by IanFla** [comment]
Hi. I would get the error when I run codes on the narval server (https://docs.alliancecan.ca/wiki/Narval/en) from the Compute Canada. I use the r/4.2.1.

**Comment by ManuelHentschel** [comment]
Could you confirm that the code from your PR works on that server?

**Comment by IanFla** [comment]
Yes. Please check the following picture about a little trial. It also shows some detailed information of the server I use. 

<img width="602" alt="cut" src="https://user-images.githubusercontent.com/51277149/190390913-1d169ad0-118c-4c21-833c-9eda7a4dc2c6.png">
